# .circleci/config.yml
version: 2.1
jobs:

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run:
          name: SwiftLint autocorrect
          command: swiftlint autocorrect
      - run:
          name: SwiftLint
          command: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml

  build-and-test:
    macos:
      xcode: "13.4.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane tests
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  screenshots:
    macos:
      xcode: "13.4.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: screenshots
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane screenshots
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  adhoc:
    macos:
      xcode: "13.4.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    shell: /bin/bash --login -o pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - 99:aa:a2:0d:88:e0:53:31:5f:73:39:a4:26:3a:b6:ad
      - checkout
      - run: bundle install
      - run:
          name: Fastlane adhoc build
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output/SunsetWorkout.ipa

  beta:
    macos:
      xcode: "13.4.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
    shell: /bin/bash --login -o pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - 99:aa:a2:0d:88:e0:53:31:5f:73:39:a4:26:3a:b6:ad
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output/SunsetWorkout.ipa

workflows:
  lint-build-test:
    jobs:
      - swiftlint
      - build-and-test
      - screenshots:
          requires:
            - build-and-test
      - adhoc:
          filters:
            branches:
              only: develop
          requires:
            - build-and-test
      #- beta:
          #filters:
            #branches:
              #only: master
          #requires:
            #- build-and-test
