# .circleci/config.yml
version: 2.1
jobs:

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run:
          name: SwiftLint autocorrect
          command: swiftlint autocorrect
      - run:
          name: SwiftLint
          command: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml

  build-and-test-iOS-15:
    macos:
      xcode: 13.4.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test_iOS_15
    steps:
      - checkout
      - run:
          name: Build and test iOS15
          command: bundle exec fastlane $FASTLANE_LANE
          environment:
            SCAN_DEVICE: iPhone 13
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  build-and-test-iOS-14:
    macos:
      xcode: 13.4.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test_iOS_14
    steps:
      - checkout
      - run:
          name: Build and test iOS14
          command: bundle exec fastlane $FASTLANE_LANE
          environment:
            SCAN_DEVICE: iPhone 13
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  build-and-test-iOS-Latest:
    macos:
      xcode: 13.4.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run:
          name: Build and test iOS14
          command: bundle exec fastlane $FASTLANE_LANE
          environment:
            SCAN_DEVICE: iPhone 13
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  lint-build-test:
    jobs:
      - swiftlint
      - build-and-test-iOS-14
      - build-and-test-iOS-15:
          requires:
            - build-and-test-iOS-14
      - build-and-test-iOS-Latest:
          requires:
            - build-and-test-iOS-15
