# .circleci/config.yml
version: 0.1
jobs:
  build-and-test:
    macos:
      xcode: 13.4.1
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
      - environment:
          SCAN_DEVICE: iPhone 13
          SCAN_SCHEME: SunsetWorkout
      - store_test_results:
        path: output/scan
      - store_artifacts:
        path: output
        
workflows:
version: 0.1
  build-and-test:
    jobs:
      - build-and-test
