# .circleci/config.yml
version: 2.1
jobs:

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run:
          name: SwiftLint autocorrect
          command: swiftlint autocorrect
      - run:
          name: SwiftLint
          command: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml

  build:
    macos:
      xcode: 13.4.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: 
          name: Install bundle
          command: bundle install
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  test:
    macos:
      xcode: 13.4.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
          environment:
            SCAN_DEVICE: iPhone 13
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  lint-build-test:
    jobs:
      - swiftlint
      - build
      - test:
          requires:
            - build
