# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 13.4.1
    #resource_class: large // Can't access this resource yet (paid resource)
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: 
          name: Install bundle
          command: bundle install
      - run:
          name: Fastlane
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 13
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build-test:
    jobs:
      - build-and-test