# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests on iOS15"
  lane :testiOS15 do
    run_tests(
      devices: ["iPhone 13", "iPhone 11", "iPhone 8", "iPhone6s"],
      scheme: "SunsetWorkout"
      )
  end

  desc "Runs all the tests on iOS14"
  lane :testiOS14 do
    scan
  end
  
end
